

name: Maizuo Test CI 
on: [push] #在推送的时候运行此action
jobs:
  # build dist and build docker image, then publish to Github Packages
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v2    #这里使用了github官方提供的action,checkout项目到虚拟机上

      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build



      # build docker image and publish to Github Packages
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ../Dockerfile
          registry: docker.pkg.github.com
          repository: wink-fe/wink-web/wink-web
          tags: master

